
[build]
  functions = "app" 
  base = "/"
  publish = "dist"
  command  = "npm run build"

[dev]
  publish = "dist"


  [[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"